name: Test

on:
  push:
    branches: [ main, fix-error-handling ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
    - name: Install dependencies
      working-directory: ./Commons
      run: npm install
    - name: Run tests
      working-directory: ./Commons
      run: npm test